apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: micuenta-front-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /frontend
        pathType: Prefix
        backend:
          service:
            name: micuenta-frontend
            port:
              number: 80